#!/bin/bash


SYSTEM=$1
if [ $SYSTEM = 'fedora' ]; then
    DEVICE="/dev/sdc3"
elif [ $SYSTEM = 'ubuntu-devel' ]; then
    DEVICE='/dev/sdb6'
elif [ $SYSTEM = 'archlinux' ]; then
    DEVICE='/dev/sdb1'
else
    echo "Enter either fedora or ubuntu-devel or archlinux"
fi

echo "Mounting filesystems"
mkdir -p /tmp/$SYSTEM
sudo mount $DEVICE /tmp/$SYSTEM
sudo mount --bind /dev /tmp/${SYSTEM}/dev
sudo mount -t proc /proc /tmp/${SYSTEM}/proc

export SHELL=/bin/sh

echo "Launching chroot"
sudo chroot /tmp/${SYSTEM} /bin/bash
#sudo chroot /tmp/${SYSTEM}

echo "Leaving chroot, unmounting filesystems"
sudo umount /tmp/${SYSTEM}/proc
sudo umount /tmp/${SYSTEM}/dev
sudo umount /tmp/${SYSTEM}
rmdir /tmp/$SYSTEM
echo "Done."
