#!/bin/sh

if [ `pgrep -u $(id -u) -f Docky.exe | wc -l` -lt 1 ]; then
    echo "Calling Docky..."
    exec docky
else
    echo "Docky appears to already be running. Restarting..."
    DOCKY_PID=`pgrep -u $(id -u) -f Docky.exe`
    echo "Docky PID is: $DOCKY_PID"
    kill -9 $DOCKY_PID
    echo "Calling Docky..."
    exec docky
fi
