#!/bin/bash

config_path=$HOME/.config/strycore
bzr_config_file="bzr.conf"
if [ ! -d $config_path ] ; then
    mkdir -p $config_path
fi

if [ "astoria" = $(hostname) ] ; then
	udisks --mount /dev/sdb1
    udisks --mount /dev/sdc1
    udisks --mount /dev/sda1
    udisks --mount /dev/sdd1
    udisks --mount /dev/sdd5
fi

function check_bzr
{

	cd $config_path
	if [ ! -f $bzr_config_file ]; then
    	touch $bzr_config_file
	fi
	for line in $(cat $bzr_config_file) ; do
    	cd $line
	    printf "[bzr] Pulling changes for "$line
    	bzr pull -q
    	printf " ... OK\n"
	done
}


function open_program
{
	name=`basename $1`
    if [ $(pgrep -lx $name | wc -l) = 0 ] ; then
		nohup $1 & > /tmp/${name}.log
		sleep 2
	fi
}

check_bzr &
cd /tmp
open_program firefox
open_program tomboy
open_program evolution
open_program terminator
