#!/bin/bash
needed_libs=$(readelf -d $1 | awk -F'[][]' '/NEEDED/{print $2}')
available_libs=$(ldconfig -p | awk '/lib32|i386|libx32/{print $1}' | sort -u)

for l in $needed_libs
do
    needed=1
    for a in $available_libs
    do
        if [ "$l" = "$a" ]; then
            needed=0
            break
        fi
    done
    if [ $needed = 1 ]; then
        echo "Missing $l"
    fi
done
