#!/bin/bash
needed_libs=$(readelf -d $1 | grep NEEDED | grep -o -e "\[.*\]" | tr -d "[]")
available_libs=$(ldconfig -p | grep -e "lib32\|i386\|libx32" | awk '{print $1}' | uniq | sort)

for l in $needed_libs
do
    needed=1
    for a in $available_libs
    do
        if [ "$l" = "$a" ]; then
            needed=0
            break
        fi
    done
    if [ $needed = 1 ]; then
        echo "Missing $l"
    fi
done
