#!/bin/bash

set -e

unmount=0
PARAMS=`getopt -n $0 -o u --long unmount --  "$@"`
eval set -- "$PARAMS"
while true ; do
    case "$1" in
        -u|--unmount) unmount=1; shift ;;
        --) shift ; break ;;
    esac
done
passfile="$HOME/.config/smbcredentials"
MOUNT=$(which mount.cifs)
if [ $(hostname) = 'astoria' ] ; then
    DESTDIR="$HOME/Shares/"
    SHARES=('video' 'applications' 'games' 'backup')
    SMB_HOST="newport"
else
    DESTDIR="$HOME/Partages/"
    SMB_HOST="nagano"
    SHARES=('qweb' 'public')
fi
if [ ! -f $passfile ] ; then
    touch $passfile
    chmod 600 $passfile
    SMB_USER=$(zenity --entry --title "Enter the username")
    SMB_PASSWD=$(zenity --password)
    echo "username="${SMB_USER} > $passfile
    echo "password="${SMB_PASSWD} >>$passfile
fi
if [ ! $MOUNT ] ; then
    echo "smbfs is not installed"
    sudo apt-get install -y smbfs
fi

for share in ${SHARES[*]} ; do
    if [ 1 = $(mount | grep ${DESTDIR}${share} | wc -l) ] ; then
      echo "$share already mounted"
      if [ $unmount = 1 ] ; then
          echo "unmounting "$share
          umount ${DESTDIR}${share}
      fi
    else
        if [ $unmount != 1 ] ; then
            echo  -ne "Mounting "
            mkdir -p ${DESTDIR}${share}
            chown ${USER}:${USER} ${DESTDIR}${share}
            full_path="//"${SMB_HOST}/${share}
            echo $full_path
        sudo mount -t cifs -o credentials=$passfile,uid=$(id -u $USER),gid=$(id -g $USER) \
        $full_path ${DESTDIR}${share}
        fi
    fi
done

