#!/bin/bash

set -e

tmp_file="/tmp/reset-mysql-password.sql"
echo -n "Enter new root password :"
read new_pass
sudo /etc/init.d/mysql stop
sudo mysqld_safe --skip-grant-tables &
echo  "use mysql;" > $tmp_file
echo "update user set password=PASSWORD(\"${new_pass}\") where User='root';" >> $tmp_file
echo "flush privileges;" >> $tmp_file
echo "quit" >> $tmp_file
mysql -u root < $tmp_file

/etc/init.d/mysql stop
rm $tmp_file
/etc/init.d/mysql start

echo "Done :)"
