#!/bin/bash

set -e

#database to populate
database=database
user=root
password=admin

dump=$1

echo "SET foreign_KEY_CHECKS=0;" > /tmp/nocheck.sql
cat /tmp/nocheck.sql $1 > /tmp/mysql_import.sql

mysql -u $user -p $password $database < /tmp/mysql_import.sql

rm /tmp/nocheck.sql
rm /tmp/mysql_import.sql
