#!/bin/bash

sudo apt-get install libjpeg-dev libfreetype6 libfreetype6-dev zlib1g-dev

sudo ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib
sudo ln -s /usr/lib/x86_64-linux-gnu/libfreetype.so /usr/lib
sudo ln -s /usr/lib/x86_64-linux-gnu/libz.so /usr/lib

echo "PIL needs to be reinstalled"

pip install -U PIL
