#!/bin/bash

set -e

if [[ "$1" == "monitor" ]]; then 
    xrandr --output HDMI-A-1 --off --output DisplayPort-2 --primary --mode 2560x1440 --rate 144 --right-of HDMI-A-1 
fi

if [[ "$1" == "tv" ]]; then 
    xrandr --output HDMI-A-1 --primary --mode 1920x1080 --rate 60 --left-of DisplayPort-2 --output DisplayPort-2 --off
fi

if [[ "$1" == "both" ]]; then 
    xrandr --output HDMI-A-1 --mode 1920x1080 --rate 60 --left-of DisplayPort-2 --output DisplayPort-2 --primary --mode 2560x1440 --rate 144
fi

