#!/bin/bash

set -e


TV_OUT="HDMI-A-1"
PC_OUT="DP-3"

if [[ "$1" == "monitor" ]]; then
    xrandr --output $TV_OUT --off --output $PC_OUT --primary --mode 2560x1440 --rate 144 --right-of $TV_OUT
fi

if [[ "$1" == "tv" ]]; then
    xrandr --output $TV_OUT --primary --mode 1920x1080 --rate 60 --left-of $PC_OUT --output $PC_OUT --off
fi

if [[ "$1" == "both" ]]; then
    xrandr --output $TV_OUT --mode 1920x1080 --rate 60 --left-of $PC_OUT --output $PC_OUT --primary --mode 2560x1440 --rate 144
fi

