#!/bin/bash
# Check if is root
if [ ! -f 'symfony' ]
    then
    echo "Please run script from project root dir"
    exit 1
fi

./symfony cc 
./symfony cc --env='prod'
./symfony cc --env='dev'


# Get working dir
MYDIR=`dirname "$0"`
if [ ! -d $MYDIR ]; then MYDIR=`dirname "$PWD/$0"`; fi

    exec ctags-exuberant -f .vimtags \
    -h ".php" -R \
    --exclude="\.svn" \
    --totals=yes \
    --tag-relative=yes \
    --PHP-kinds=+cf \
    --regex-PHP='/abstract class ([^ ]*)/\1/c/' \
    --regex-PHP='/interface ([^ ]*)/\1/c/' \
    --regex-PHP='/(public |static |abstract |protected |private )+function ([^ (]*)/\2/f/'
