#!/bin/bash

set -e


SYMFONY_VERSION='1.4.8'
SYMFONY_TGZ_CHECKSUM='0d17b1ef8b9e02d196fdb528c443ccd8'
SYMFONY_FILENAME="symfony-$SYMFONY_VERSION.tgz"
SYMFONY_CURRENT_URL="http://www.symfony-project.org/get/$SYMFONY_FILENAME"
SQL_PASSWORD=boesneradmin
SQL_ROOT_PASSWORD='admin'
HOSTNAME=`hostname`
EMAIL='mathieu@a2v.eu'
ENABLE_SFGUARD_PLUGIN=true

BASEDIR=`pwd`

echo "Enter your project's name :"
read PROJECT
PROJECT_DIR=$BASEDIR"/"$PROJECT
echo "Project will be saved in $PROJECT_DIR ; is this correct ? (y/N)"
read ANSWER
if [ $ANSWER != 'y' ] ; then
    exit 2
fi

DATABASE=$PROJECT

if [ -d $PROJECT_DIR ]; then
    echo "Destination directory already exists, quitting"
    exit 2
fi

SYMFONY_PATH=/tmp/$SYMFONY_FILENAME
wget $SYMFONY_CURRENT_URL -O $SYMFONY_PATH
mkdir -p $PROJECT_DIR/lib
cd $PROJECT_DIR/lib
tar xvzf $SYMFONY_PATH
mv symfony-$SYMFONY_VERSION symfony
cd ..

./lib/symfony/data/bin/symfony generate:project $PROJECT

cd data
echo "Setting up mysql"
cat > create_user.sql << EOF
 GRANT USAGE ON *.* TO '$DATABASE'@'localhost';
 DROP USER '$DATABASE'@'localhost';
 DROP DATABASE IF EXISTS $DATABASE ;
 CREATE USER '$DATABASE'@'localhost' IDENTIFIED BY '$SQL_PASSWORD';
 GRANT USAGE ON * . * TO '$DATABASE'@'localhost' IDENTIFIED BY '$SQL_PASSWORD' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0   MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
 CREATE DATABASE IF NOT EXISTS $DATABASE;
 GRANT ALL PRIVILEGES ON $DATABASE . * TO '$DATABASE'@'localhost';
EOF
mysql -uroot -p$SQL_ROOT_PASSWORD < create_user.sql
echo "Setting up Apache"
cat > $PROJECT.vhost << EOF
<VirtualHost *:80>
	ServerAdmin $EMAIL
	ServerName $PROJECT.$HOSTNAME
	DocumentRoot $PROJECT_DIR/web/
	<Directory $PROJECT_DIR/web/>
		Options Indexes FollowSymLinks MultiViews
		AllowOverride None
		Order allow,deny
		allow from all
	</Directory>
	Alias /sf $PROJECT_DIR/lib/symfony/data/web/sf
	<Directory "$PROJECT_DIR/lib/symfony/data/web/sf">
	    AllowOverride All
	    Allow from All
	</Directory>
	ErrorLog /var/log/apache2/${PROJECT}_error.log
	LogLevel warn
	CustomLog /var/log/apache2/${PROJECT}_access.log combined
</VirtualHost>
EOF

sudo cp $PROJECT.vhost /etc/apache2/sites-available/$PROJECT
sudo a2ensite $PROJECT
sudo /etc/init.d/apache2 reload
echo "Setting up Host"
if [ $(grep $PROJECT.$HOSTNAME /etc/hosts | wc -l) = 0 ]
  then
    echo "127.0.0.1  $PROJECT.$HOSTNAME " | sudo tee -a /etc/hosts
fi


echo "Creating frontend"
cd ..
./symfony configure:database --name=doctrine --class=sfDoctrineDatabase "mysql:host=localhost;dbname=$DATABASE" $DATABASE $SQL_PASSWORD
./symfony generate:app frontend
./symfony cc

if [ $ENABLE_SFGUARD_PLUGIN ]
  then
    echo "Installing sfGuard"
    ./symfony plugin:install sfDoctrineGuardPlugin
    ./symfony doctrine:build-model
    ./symfony doctrine:build-sql
    ./symfony doctrine:insert-sql
fi

chmod -R 777 log
chmod -R 777 cache

echo "Init bzr"
bzr init
bzr ignore log/*
bzr ignore cache/*
bzr ignore lib/symfony/*
bzr add *
bzr commit -m "First commit"


