#!/bin/bash

set -e

cp $HOME/bin/vimrc $HOME/.vimrc

mkdir -p $HOME/.fonts
mkdir -p $HOME/.vim/plugin
mkdir -p $HOME/.vim/colors
mkdir -p $HOME/.vim/syntax
mkdir -p $HOME/.vim/snippets

cd $HOME/.vim

if [ ! -f ./plugin/NERD_tree.vim ] ; then
    wget http://www.vim.org/scripts/download_script.php?src_id=9870 -O NERD_tree.zip
    unzip NERD_tree.zip
    rm NERD_tree.zip
fi

if [ ! -f ./plugin/minibufexpl.vim ] ; then
    wget http://www.vim.org/scripts/download_script.php?src_id=3640 -O ./plugin/minibufexpl.vim
fi

if [ ! -f ./plugin/taglist.vim ] ; then
    wget "http://vim.sourceforge.net/scripts/download_script.php?src_id=7701" -O taglist_45.zip
    unzip taglist_45.zip
    rm taglist_45.zip
fi

if [ ! -f ./plugin/project.vim ]; then
    wget http://www.vim.org/scripts/download_script.php?src_id=6273 -O project-1.4.1.tar.gz
    tar xzf project-1.4.1.tar.gz
    rm project-1.4.1.tar.gz
fi

# Fonts
if [ ! -f $HOME/.fonts/Inconsolata.otf ] ; then
    wget "http://www.fontex.org/get/Inconsolata.otf" -O $HOME/.fonts/Inconsolata.otf
fi

# Color schemes
if [ ! -f ./colors/desert256.vim ] ; then
    wget "http://www.vim.org/scripts/download_script.php?src_id=4055" -O ./colors/desert256.vim
fi

if [ ! -f ./colors/railscasts.vim ] ; then
    wget "http://www.vim.org/scripts/download_script.php?src_id=8379" -O ./colors/railscasts.vim
fi

if [ ! -f ./colors/wombat.vim ] ; then
    wget "http://www.vim.org/scripts/download_script.php?src_id=6657" -O ./colors/wombat.vim
fi

if [ ! -f ./colors/wombat256.vim ] ; then
    wget "http://www.vim.org/scripts/download_script.php?src_id=13397" -O ./colors/wombat256.vim
fi

if [ ! -f ./colors/wombat256mod.vim ] ; then
    wget "http://www.vim.org/scripts/download_script.php?src_id=13400" -O ./colors/wombat256mod.vim
fi

if [ ! -f ./colors/tango.vim ] ; then
    wget "http://www.vim.org/scripts/download_script.php?src_id=6361" -O ./colors/tango.vim
fi

if [ ! -f ./colors/django.vim ] ; then
    wget "http://www.vim.org/scripts/download_script.php?src_id=7015" -O ./colors/django.vim
fi

if [ ! -f ./colors/molokai.vim ] ; then
    wget "http://www.vim.org/scripts/download_script.php?src_id=9750" -O ./colors/molokai.vim
fi

if [ ! -f ./colors/solarized.vim ] ; then
    wget "http://www.vim.org/scripts/download_script.php?src_id=15285" -O vim-colors-solarized-v1.0.0beta1.zip
    unzip vim-colors-solarized-v1.0.0beta1.zip
    mv vim-colors-solarized/colors/solarized.vim ./colors/
    rm -rf vim-colors-solarized
    rm vim-colors-solarized-v1.0.0beta1.zip
fi

#

if [ ! -f ./plugin/symfony.vim ] ; then
    wget "http://www.vim.org/scripts/download_script.php?src_id=8739" -O ./plugin/symfony.vim
fi

if [ ! -f ./ack.tar.gz ] ; then
    wget "http://www.vim.org/scripts/download_script.php?src_id=10433" -O ./ack.tar.gz
    tar xzf ack.tar.gz
fi

if [ ! -f ./plugin/zencoding.vim ] ; then
    wget "http://www.vim.org/scripts/download_script.php?src_id=13765" -O ./plugin/zencoding.vim
fi

if [ ! -f ./plugin/snipMate.vim ] ; then
    wget "http://www.vim.org/scripts/download_script.php?src_id=11006" -O ./snipMate.zip
    unzip ./snipMate.zip
    rm -rf ./snipMate.zip
fi

if [ ! -f ./plugin/surround.vim ] ; then
    wget "http://www.vim.org/scripts/download_script.php?src_id=12566" -O ./surround.zip
    unzip ./surround.zip
    rm ./surround.zip
fi

if [ ! -f ./syntax/vala.vim ] ; then
    wget "http://live.gnome.org/Vala/Vim?action=AttachFile&do=get&target=vala.vim"  -O ./syntax/vala.vim
fi

if [ ! -f ./syntax/python.vim ] ; then
    wget "http://www.vim.org/scripts/download_script.php?src_id=12804" -O ./syntax/python.vim
fi

if [ ! -f ./snippets/htmldjango.snippets ] ; then
    git clone https://github.com/robhudson/snipmate_for_django.git
    cp snipmate_for_django/snippets/htmldjango.snippets ./snippets/
    cp snipmate_for_django/snippets/django.snippets ./snippets/
    rm -rf snipmate_for_django
fi

if [ ! -f $(which php_beautifier) ] ; then
    sudo pear install PHP_Beautifier-0.1.15
fi
if [ $(which apt-get) ] ; then
  INSTALLER="apt-get"
fi
if [ $INSTALLER ] ; then
    if [ -z $(which ctags) ] ; then
        sudo apt-get install ctags
    fi

    if [ $(python -c "import rope" 2>&1 | grep ImportError | wc -c) -gt 0 ] ; then
        sudo apt-get install python-rope
    fi
fi
